name: 'CD - Deploy Dev Infra'

on:
  workflow_run:
    workflows: ["CI - Branch-Specific Validation"]
    types: [completed]
  workflow_dispatch:
    inputs:
      action:
        description: 'Deployment Action'
        required: true
        default: 'apply'
        type: choice
        options:
        - plan
        - apply
        - destroy

env:
  ENVIRONMENT: dev

jobs:

  deploy-dev:
    name: 'Deploy to Development'
    runs-on: self-hosted
    if: github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.head_branch == 'develop')
    environment: development
    steps:
      - name: Print Branch Info
        run: echo "Branch: ${{ github.event.workflow_run.head_branch }}"

    environment: development
    
    defaults:
      run:
        working-directory: azure/code/dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.ref }}


      - name: Terraform Init
        run: |
          echo "=== Terraform Init ==="
          terraform init

      - name: Terraform Plan
        if: github.event.inputs.action == 'plan' || github.event_name == 'workflow_run'
        run: terraform plan -out=tfplan

      - name: Upload Plan (for workflow_run)
        if: github.event_name == 'workflow_run'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: azure/code/dev/tfplan

      - name: Download Plan
        if: github.event.inputs.action == 'apply' || github.event_name == 'workflow_run'
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: azure/code/dev/

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply' || github.event_name == 'workflow_run'
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: |
          echo "=== Destroying Development Environment ==="
          o "This action cannot be undone!"
          terraform destroy -auto-approve

      - name: Post-Deployment AKS Check
        if: (github.event.inputs.action == 'apply' || github.event_name == 'workflow_run') && success()
        run: |
          echo "=== Post-Deployment Tasks ==="
          
          # Get cluster info from Terraform outputs
          CLUSTER_NAME=$(terraform output -raw cluster_name)
          RG_NAME=$(terraform output -raw resource_group_name)
          
          echo "Cluster: $CLUSTER_NAME"
          echo "Resource Group: $RG_NAME"
          
          # Get kubectl config using outputs
          az aks get-credentials --resource-group "$RG_NAME" --name "$CLUSTER_NAME" --overwrite-existing
          
          # Wait for cluster readiness
          kubectl wait --for=condition=Ready nodes --all --timeout=300s

      - name: Deployment Summary
        if: always()
        run: |
          echo "=== Development Deployment Summary ==="
          echo "Environment: ${{ env.ENVIRONMENT }}"
          echo "Trigger: ${{ github.event_name }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch || github.ref_name }}"
          
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            echo "Action: apply (auto)"
            echo "Status: AUTO-DEPLOYED via CI"
          else
            echo "Action: ${{ github.event.inputs.action }}"
            if [ "${{ github.event.inputs.action }}" = "apply" ]; then
              echo "Status: DEPLOYED"
            elif [ "${{ github.event.inputs.action }}" = "destroy" ]; then
              echo "Status: DESTROYED"
            else
              echo "Status: PLANNED"
            fi
          fi
          
          echo "Timestamp: $(date)"