name: 'CD - Deploy Prod Infra'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Deployment Action'
        required: true
        default: 'apply'
        type: choice
        options:
        - plan
        - apply
        - destroy

env:
  ENVIRONMENT: prod

jobs:
  deploy-prod:
    name: 'Deploy to Production'
    runs-on: self-hosted
    environment: production
    defaults:
      run:
        working-directory: azure/code/prod
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: |
          echo "=== Terraform Init ==="
          terraform init

      - name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        run: |
          echo "=== Terraform Plan ==="
          terraform plan -out=tfplan

      - name: Manual Approval
        if: github.event.inputs.action == 'apply'
        run: |
          echo "Waiting for manual approval before applying to production."
          echo "Approve this job in the GitHub Actions UI to continue."

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: |
          echo "=== Applying to Production Environment ==="
          terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: |
          echo "=== Destroying Production Environment ==="
          echo "This action cannot be undone!"
          terraform destroy -auto-approve

      - name: Post-Deployment AKS Check
        if: (github.event.inputs.action == 'apply' && success())  
        run: |
          echo "=== Post-Deployment Tasks ==="
          CLUSTER_NAME=$(terraform output -raw cluster_name)
          RG_NAME=$(terraform output -raw resource_group_name)
          echo "Cluster: $CLUSTER_NAME"
          echo "Resource Group: $RG_NAME"
          az aks get-credentials --resource-group "$RG_NAME" --name "$CLUSTER_NAME" --overwrite-existing
          kubectl wait --for=condition=Ready nodes --all --timeout=300s

      - name: Deployment Summary
        if: always()
        run: |
          echo "=== Production Deployment Summary ==="
          echo "Environment: ${{ env.ENVIRONMENT }}"
          echo "Trigger: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            echo "Action: apply (auto)"
            echo "Status: AUTO-DEPLOYED via CI"
          else
            echo "Action: ${{ github.event.inputs.action }}"
            if [ "${{ github.event.inputs.action }}" = "apply" ]; then
              echo "Status: DEPLOYED"
            elif [ "${{ github.event.inputs.action }}" = "destroy" ]; then
              echo "Status: DESTROYED"
            else
              echo "Status: PLANNED"
            fi
          fi
          echo "Timestamp: $(date)"